// @flow

export default {
  WindowStyleSingle: 'Überwiegend Einfachverglasung',
  WindowStyleInsulating: 'Überwiegend Wärmeschutzverglasung (Einbau ab 1995) oder Schallschutzfenster für Wohngebäude/Wohnungen, die vor 1995 bezugsfertig geworden sind',
  HighGradeFlooring: 'Hochwertiges Parkett, Natur-/Kunststein, Fliesen oder gleichwertiger Boden/-belag in der überwiegenden Zahl der Wohnräume',
  InsufficientPower: 'Unzureichende Elektroinstallation, z.B. keine ausreichende Elektrosteigleitung und/oder VDE gerechte Elektroinstallation (z.B. kein FI-Schalter, Potentialausgleich)',
  WallInstallationElectrical: 'Elektroinstallation überwiegend sichtbar auf Putz',
  WallInstallationDrainage: 'Be- und Entwässerungsinstallation überwiegend auf Putz',
  WallInstallationHeating: 'Heizungsrohre überwiegend nicht sichtbar',
  ColdWaterMetering: 'Wohnungsbezogener Kaltwasserzähler in vor 1998 bezugsfertigen Gebäuden/Wohnungen, wenn der Mieter nicht die Kosten für Miete oder Leasing im Rahmen der Betriebskosten trägt',
  BadFlatDesign: 'Schlechter Schnitt (z.B. gefangener Raum und/oder Durchgangsraum)',
  StorageCabinet: 'Einbauschrank oder Abstellraum innerhalb der Wohnung',
  NoSpaceForWashing: 'Waschmaschine weder in Bad noch Küche stellbar oder nicht anschließbar',
  LargeLiving: 'Großer, geräumiger Balkon, (Dach-)Terrasse, Loggia oder Winter-/Dachgarten (ab 4 m²)',
  AccessibleDesign: 'Barrierearme Wohnungsgestaltung (Schwellenfreiheit in der Wohnung, schwellenarmer Übergang zu Balkon/Terrasse, ausreichende Bewegungsfreiheit in der Wohnung und/oder barrierearme Badgestaltung)',
  NoBalcony: 'Kein Balkon, (Dach-)Terrasse, Loggia und Winter-/Dachgarten (gilt nicht, wenn das Merkmal aus baulichen und/oder rechtlichen Gründen nicht möglich oder nicht zulässig ist)',
  SpaciousBalcony: 'Großer, geräumiger Balkon, (Dach-)Terrasse, Loggia oder Winter-/Dachgarten (ab 4 m²)',
  RollingShutters: 'Rollläden',
  CeilingDecoration: 'Aufwändige Decken- und/oder Wandverkleidung (z.B. Stuck, Täfelung) in gutem Zustand in der überwiegenden Anzahl der Wohnräume',
  AntiBurglary: 'Zusätzliche Einbruchsicherung für die Wohnungstür bei verstärkten Türen',

  TinySink: 'Kein Handwaschbecken in Bad oder WC oder im Bad nur ein kleines Handwaschbecken',
  ToiletNoVentilation: 'WC ohne Lüftungsmöglichkeit oder Entlüftung',
  BoardFlooring: 'Dielenfußboden im Bad',
  WarmWater: 'Keine ausreichende Warmwasserversorgung',
  FixedBathtub: 'Einbauwanne',
  InsufficientTiling: 'Wände nicht ausreichend im Spritzwasserbereich von Waschbecken, Badewanne und/oder Dusche gefliest',
  NoWindows: 'Bad mit WC ohne Fenster',
  NoShower: 'Keine Duschmöglichkeit',
  TinyBath: 'Kleines Bad',
  LargeSink: 'Sehr großes Waschbecken (Außenmaß mindestens 80 cm breit) oder Doppelhandwaschbecken oder zwei getrennte Waschbecken',
  HighClassFeatures: 'Besondere und hochwertige Ausstattung',
  ElectronicVentilation: 'Innen liegendes Badezimmer mit moderner, gesteuerter Entlüftung ',
  AdditionalWC: 'Zweites WC in der Wohnung oder Bad und WC getrennt',
  LargeBath: 'Mindestens ein Bad größer als 8 m²',
  FloorHeating: 'Fußbodenheizung',
  HighClassTiling: 'Wandbekleidung und Bodenbelag hochwertig',
  WallMountedWC: 'Wandhängendes WC mit in der Wand eingelassenem Spülkasten',
  TowelHeating: 'Strukturheizkörper als Handtuchwärmer',
  AdditionalShower: 'Von der Badewanne getrennte zusätzliche Duschtasse oder -kabine',

  EntranceCondition: 'Treppenhaus/Eingangsbereich überwiegend in schlechtem Zustand',
  DoorLock: 'Hauseingangstür nicht abschließbar',
  RepresentativeEntrance: 'Repräsentativer/s oder hochwertig sanierter/s Eingangsbereich/Treppenhaus',
  WellMaintained: 'Überdurchschnittlich guter Instandhaltungszustand des Gebäude (-teil-)s, in dem sich die Wohnung befindet',
  NoStorageRoom: 'Kein Mieterkeller oder Kellerersatzraum zur alleinigen Nutzung des Mieters vorhanden',
  BicycleRoom: 'Abschließbarer leicht zugänglicher Fahrradabstellraum innerhalb des Gebäudes oder Fahrradabstellplätze mit Anschließmöglichkeit außerhalb des Gebäudes auf dem Grundstück',
  CommunalSpace: 'Zusätzliche und in angemessenem Umfang nutzbare Räume außerhalb der Wohnung in fußläufiger Entfernung',
  LowMaintenance: 'Schlechter Instandhaltungszustand ',
  SideWing: 'Lage im Seitenflügel oder Quergebäude bei verdichteter Bebauung',
  NoLift: 'Wohnung ab fünftem Obergeschoss ohne Personenaufzug',
  Lift: 'Personenaufzug bei weniger als fünf Obergeschossen',
  NoIntercom: 'Keine Gegen-/Wechselsprechanlage mit elektrischem Türöffner',
  IntercomVideo: 'Gegen-/Wechselsprechanlage mit Videokontakt und elektrischem Türöffner',
  ModernizedHeatingSystem: 'Wärmedämmung zusätzlich zur vorhandenen Bausubstanz oder Einbau/Installation einer modernen Heizanlage ab 01.01.2003 ',
  InsufficientInsulation: 'Unzureichende Wärmedämmung oder Heizanlage mit ungünstigem Wirkungsgrad',
  Sub80: 'Energieverbrauchskennwert < 80 kWh/(m²a)',
  Sub100: 'Energieverbrauchskennwert < 100 kWh/(m²a)',
  Sub120: 'Energieverbrauchskennwert < 120 kWh/(m²a)',
  Super155: 'Energieverbrauchskennwert > 155 kWh/(m²a)',
  Super195: 'Energieverbrauchskennwert > 195 kWh/(m²a)',
  Super235: 'Energieverbrauchskennwert > 235 kWh/(m²a)',

  QuietStreet: 'Besonders ruhige Lage',
  Noisy: 'Besonders lärmbelastete Lage',
  Smelly: 'Besonders geruchsbelastete Lage',
  PrimeDowntown: 'Bevorzugte Citylage',
  NeglectedArea: 'Lage in stark vernachlässigter Umgebung in einfacher Wohnlage',
  NeatoBackyard: 'Aufwändig gestaltetes Wohnumfeld auf dem Grundstück ',
  PrivateBackyard: 'Garten zur alleinigen Nutzung/Mietergarten ohne Entgelt oder zur Wohnung gehörender Garten mit direktem Zugang',
  BicycleParking: 'Keine Fahrradabstellmöglichkeit auf dem Grundstück',
  Parking: 'Vom Vermieter zur Verfügung gestelltes PKW-Parkplatzangebot in der Nähe',

  NoVentilation: 'Küche ohne Fenster und ohne ausreichende Entlüftung',
  ExtractorHood: 'Dunstabzug',
  NoHeating: 'Küche nicht beheizbar oder Holz-/Kohleheizung',
  HighGradeFloor: 'Hochwertige Fliesen, hochwertiges Linoleum, hochwertiges Feuchtraumlaminat, Parkett, Terrazzo als Bodenbelag jeweils in gutem Zustand',
  FittedKitchen: 'Einbauküche mit Ober- und Unterschränken sowie Herd und Spüle',
  KitchenLiving: 'Separate Küche mit mind. 14 m² Grundfläche',
  NoStove: 'Keine Kochmöglichkeit oder Gas-/Elektroherd ohne Backofen',
  HighGradeStove: 'Ceran-Kochfeld oder Induktions-Kochfeld',
  NoSink: 'Keine Spüle',
  NoDishwasherSpace: 'Geschirrspüler in der Küche nicht stellbar oder anschließbar',
  FreezerProvided: 'Kühlschrank',
  InsufficientWarmWater: 'Keine ausreichende Warmwasserversorgung'
}